import decimal
import xml.etree.ElementTree as ET
from .constraint import Intervals, Pattern
from .exceptions import InvalidArgument, InvalidLeafrefPath, MissingModuleNamespace, ModuleNotRegistered, ParserException, UnknownPrefix
from .instance import InstanceIdParser, InstanceNode, InstanceRoute
from .schemadata import SchemaContext
from .schemanode import TerminalNode, DataNode, SchemaNode
from .statement import Statement
from .typealiases import QualName, RawScalar, ScalarValue, YangIdentifier
from .xpathast import Expr
from .xpathparser import XPathParser
from typing import Any, Optional, Union
import typing

class DataType:
    sctx: SchemaContext
    default: Optional[ScalarValue]
    name: Optional[YangIdentifier]
    error_tag: Optional[str]
    error_message: Optional[str]
    units: Optional[str]
    def __init__(self, sctx: SchemaContext, name: Optional[YangIdentifier]) -> None: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def to_raw(self, val: ScalarValue) -> Optional[RawScalar]: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...
    def parse_value(self, text: str) -> Optional[ScalarValue]: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...
    def from_yang(self, text: str) -> ScalarValue: ...
    def yang_type(self) -> YangIdentifier: ...

class EmptyType(DataType):
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def parse_value(self, text: str) -> Optional[tuple[None]]: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def to_raw(self, val: ScalarValue) ->  Optional[RawScalar]: ...
    def from_xml(self, xml: ET.Element) -> Optional[tuple[None]]: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...

class BitsType(DataType):
    bit: dict[YangIdentifier, int]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def sorted_bits(self) -> list[tuple[str, int]]: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def to_raw(self, val: ScalarValue) -> Optional[RawScalar]: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...
    def as_int(self, val: ScalarValue) -> int: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...

class BooleanType(DataType):
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def parse_value(self, text: str) -> Optional[bool]: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...

class LinearType(DataType):
    length: Optional[Intervals]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...

class StringType(LinearType):
    patterns: list[Pattern]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...

class BinaryType(LinearType):
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def to_raw(self, val: ScalarValue) -> Optional[RawScalar]: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...

class EnumerationType(DataType):
    enum: dict[str, int]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def sorted_enums(self) -> list[tuple[str, int]]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...

class LinkType(DataType):
    require_instance: bool
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...

class LeafrefType(LinkType):
    path: Optional[Expr]
    ref_type: Optional["DataNode"]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def to_raw(self, val: ScalarValue) -> RawScalar: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...
    def parse_value(self, text: str) -> Optional[ScalarValue]: ...
    def from_yang(self, text: str) -> ScalarValue: ...

class InstanceIdentifierType(LinkType):
    root: Optional[SchemaNode]
    def yang_type(self) -> YangIdentifier: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def to_raw(self, val: ScalarValue) -> Optional[str]: ...
    def to_xml(self, val: ScalarValue) -> Optional[str]: ...
    def from_yang(self, text: str) -> ScalarValue: ...

class IdentityrefType(DataType):
    bases: list[QualName]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def to_raw(self, val: ScalarValue) -> Optional[str]: ...
    def to_xml(self, val: ScalarValue) -> str: ...
    def from_yang(self, text: str) -> ScalarValue: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...

class NumericType(DataType):
    range: Optional[Intervals]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...

class Decimal64Type(NumericType):
    fraction_digits: int
    _epsilon: decimal.Decimal
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[decimal.Decimal]: ...
    def to_raw(self, val: ScalarValue) -> Optional[str]: ...
    def to_xml(self, val: ScalarValue) -> str: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...

class IntegralType(NumericType):
    octhex: typing.Pattern[str]
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
    def parse_value(self, text: str) -> Optional[int]: ...
    def from_raw(self, raw: RawScalar) -> Optional[int]: ...
    def from_xml(self, xml: ET.Element) -> Optional[int]: ...
    def from_yang(self, text: str) -> int: ...

class Int8Type(IntegralType): ...
class Int16Type(IntegralType): ...
class Int32Type(IntegralType): ...

class Int64Type(IntegralType):
    def from_raw(self, raw: RawScalar) -> Optional[int]: ...
    def from_xml(self, xml: ET.Element) -> Optional[int]: ...
    def to_raw(self, val: ScalarValue) -> str: ...
    def to_xml(self, val: ScalarValue) -> str: ...

class Uint8Type(IntegralType): ...
class Uint16Type(IntegralType): ...
class Uint32Type(IntegralType): ...

class Uint64Type(IntegralType):
    def from_raw(self, raw: RawScalar) -> Optional[int]: ...
    def from_xml(self, xml: ET.Element) -> Optional[int]: ...
    def to_raw(self, val: ScalarValue) -> str: ...
    def to_xml(self, val: ScalarValue) -> str: ...

class UnionType(DataType):
    types: list[DataType]
    def __init__(self, sctx: SchemaContext, name: YangIdentifier) -> None: ...
    def to_raw(self, val: ScalarValue) -> RawScalar: ...
    def to_xml(self, val: ScalarValue) -> str: ...
    def canonical_string(self, val: ScalarValue) -> Optional[str]: ...
    def parse_value(self, text: str) -> Optional[ScalarValue]: ...
    def from_raw(self, raw: RawScalar) -> Optional[ScalarValue]: ...
    def from_xml(self, xml: ET.Element) -> Optional[ScalarValue]: ...
    def __contains__(self, val: Union[ScalarValue, InstanceRoute]) -> bool: ...
