import xml.etree.ElementTree as ET
from .enumerations import ContentType, ValidationScope
from .exceptions import InstanceException as InstanceException, InstanceValueError as InstanceValueError, NonexistentInstance as NonexistentInstance
from .instvalue import ArrayValue, InstanceKey, ObjectValue, ScalarValue, Value
from .parser import Parser
from .schemadata import SchemaData
from .schemanode import DataNode
from .typealiases import InstanceName, JSONPointer, QualName, RawValue, YangIdentifier, _Singleton
from _typeshed import Incomplete
from datetime import datetime
from typing import Any, TypeVar, Generic, Iterator, Tuple, Union, Optional, NoReturn

__all__ = ['InstanceNode', 'RootNode', 'ObjectMember', 'ArrayEntry', 'EntryValue', 'InstanceIdParser', 'ResourceIdParser', 'InstanceRoute', 'InstanceException', 'InstanceValueError', 'NonexistentInstance']

class OutputFilter:
    def begin_member(self, parent: InstanceNode, node: InstanceNode, attributes: dict[str, Any]) -> bool: ...
    def end_member(self, parent: InstanceNode, node: InstanceNode, attributes: dict[str, Any]) -> bool: ...
    def begin_element(self, parent: InstanceNode, node: InstanceNode, attributes: dict[str, Any]) -> bool: ...
    def end_element(self, parent: InstanceNode, node: InstanceNode, attributes: dict[str, Any]) -> bool: ...

T = TypeVar("T")
class LinkedList(Generic[T]):
    @classmethod
    def from_list(cls, vals: list[Value] = [], reverse: bool = False) -> LinkedList[T]: ...
    head: Incomplete
    tail: Incomplete
    def __init__(self, head: Value, tail: LinkedList[T]) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def cons(self, val: Value) -> LinkedList[T]: ...
    def pop(self) -> tuple[Value, 'LinkedList[T]']: ...

class EmptyList(LinkedList[T], metaclass=_Singleton):
    def __init__(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, key: int) -> T: ...
    def pop(self) -> Tuple[Any, LinkedList[T]]: ...

class InstanceNode:
    parinst: InstanceNode | None
    schema_node: DataNode
    schema_data: Incomplete
    timestamp: datetime
    value: Value
    def __init__(self, key: InstanceKey, value: Value, parinst: InstanceNode | None, schema_node: DataNode, timestamp: datetime) -> None: ...
    @property
    def name(self) -> InstanceName: ...
    @property
    def namespace(self) -> YangIdentifier | None: ...
    @property
    def path(self) -> tuple[InstanceKey]: ...
    def __getitem__(self, key: InstanceKey) -> InstanceNode: ...
    def __iter__(self) -> Iterator[Union[str, Value]]: ...
    def json_pointer(self) -> JSONPointer: ...
    def instance_route(self) -> InstanceRoute: ...
    def is_internal(self) -> bool: ...
    def put_member(self, name: InstanceName, value: Value, raw: bool = False) -> InstanceNode: ...
    def delete_item(self, key: InstanceKey) -> InstanceNode: ...
    def up(self) -> InstanceNode: ...
    def top(self) -> InstanceNode: ...
    def update(self, value: RawValue | Value, raw: bool = False) -> InstanceNode: ...
    def merge(self, value: RawValue | Value, raw: bool = False) -> InstanceNode: ...
    def goto(self, iroute: InstanceRoute) -> InstanceNode: ...
    def peek(self, iroute: InstanceRoute) -> Value | None: ...
    def validate(self, scope: ValidationScope = ..., ctype: ContentType = ...) -> None: ...
    def add_defaults(self, ctype: Optional[ContentType] = None, tag: bool = False) -> InstanceNode: ...
    def raw_value(self, filter: OutputFilter = ...) -> RawValue: ...
    def to_xml(self, filter: OutputFilter = ..., elem: Optional[ET.Element] = None) -> ET.Element: ...

class RootNode(InstanceNode):
    schema_data: Incomplete
    def __init__(self, value: Value, schema_node: DataNode, schema_data: SchemaData, timestamp: datetime) -> None: ...
    @property
    def namespace(self) -> None: ...
    def up(self) -> NoReturn: ...
    def to_xml(self, filter: OutputFilter = ..., tag: str = 'content-data', urn: str = 'urn:ietf:params:xml:ns:yang:ietf-yang-instance-data') -> ET.Element: ... # type: ignore[override]

class ObjectMember(InstanceNode):
    siblings: dict[InstanceName, Value]
    def __init__(self, key: InstanceName, siblings: dict[InstanceName, Value], value: Value, parinst: InstanceNode | None, schema_node: DataNode, timestamp: datetime) -> None: ...
    @property
    def qual_name(self) -> QualName: ...
    def sibling(self, name: InstanceName) -> ObjectMember: ...
    def look_up(self, raw: bool = False, /, **keys: dict[InstanceName, ScalarValue]) -> ArrayEntry: ...

class ArrayEntry(InstanceNode):
    before: LinkedList[Value]
    after: LinkedList[Value]
    def __init__(self, key: int, before: LinkedList[Value], after: LinkedList[Value], value: Value, parinst: Optional[InstanceNode], schema_node: DataNode, timestamp: Optional[datetime] = None) -> None: ...
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> InstanceName: ...
    @property
    def qual_name(self) -> QualName | None: ...
    def update(self, value: RawValue | Value, raw: bool = False) -> ArrayEntry: ...
    def previous(self) -> ArrayEntry: ...
    def next(self) -> ArrayEntry: ...
    def insert_before(self, value: RawValue | Value, raw: bool = False) -> ArrayEntry: ...
    def insert_after(self, value: RawValue | Value, raw: bool = False) -> ArrayEntry: ...

class InstanceRoute(list["MemberName"]):
    def __hash__(self) -> int: ... # type: ignore[override]

class MemberName:
    name: Incomplete
    namespace: Incomplete
    def __init__(self, name: YangIdentifier, ns: YangIdentifier | None) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def iname(self) -> str: ...
    def peek_step(self, val: ObjectValue, sn: DataNode) -> tuple[Optional[Value], 'DataNode']: ...
    def goto_step(self, inst: InstanceNode) -> InstanceNode: ...

class ActionName(MemberName):
    def peek_step(self, val: ObjectValue, sn: DataNode) -> tuple[None, 'DataNode']: ...
    def goto_step(self, inst: InstanceNode) -> NoReturn: ...

class EntryIndex:
    index: Incomplete
    def __init__(self, index: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def peek_step(self, val: ArrayValue, sn: DataNode) -> tuple[Value | None, 'DataNode']: ...
    def goto_step(self, inst: InstanceNode) -> InstanceNode: ...

class EntryValue:
    value: Incomplete
    def __init__(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def parse_value(self, sn: DataNode) -> ScalarValue: ...
    def peek_step(self, val: ArrayValue, sn: DataNode) -> tuple[Value, 'DataNode']: ...
    def goto_step(self, inst: InstanceNode) -> InstanceNode: ...

class EntryKeys:
    keys: Incomplete
    def __init__(self, keys: dict[tuple[YangIdentifier, YangIdentifier | None], str]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def parse_keys(self, sn: DataNode) -> dict[InstanceName, ScalarValue]: ...
    def peek_step(self, val: ArrayValue, sn: DataNode) -> tuple[ObjectValue, 'DataNode']: ...
    def goto_step(self, inst: InstanceNode) -> InstanceNode: ...

class ResourceIdParser(Parser):
    schema_node: Incomplete
    def __init__(self, text: str, sn: DataNode) -> None: ...
    def parse(self) -> InstanceRoute: ...

class InstanceIdParser(Parser):
    def parse(self) -> InstanceRoute: ...
